import type { McpGraphDocument } from "../model/McpGraphDocument"
import type { McpTraceDocument } from "../model/McpTraceDocument"

const graph = {
  schemaVersion: "1",
  id: "field-research-gateway",
  name: "Field research gateway",
  description: "Route a client request through a gateway to a task-backed vertical server",
  nodes: [
    {
      id: "client",
      kind: "client",
      label: "Research client",
      description: "Calls the field research tool",
      position: { x: 80, y: 220 },
      config: { transport: "streamable-http" },
    },
    {
      id: "gateway",
      kind: "gateway",
      label: "Capability gateway",
      description: "Routes the request by capability",
      position: { x: 330, y: 220 },
      config: { strategy: "capability" },
    },
    {
      id: "server",
      kind: "server",
      label: "Field operations",
      description: "A vertical MCP server for field research",
      position: { x: 590, y: 220 },
      config: { domain: "field-operations" },
    },
    {
      id: "tool",
      kind: "tool",
      label: "research.site",
      description: "Collect observations for a site",
      position: { x: 850, y: 140 },
      config: { resultType: "task" },
    },
    {
      id: "task",
      kind: "task",
      label: "Site research task",
      description: "Tracks asynchronous work to completion",
      position: { x: 850, y: 330 },
      config: { pollingIntervalMs: 1000 },
    },
  ],
  edges: [
    { id: "client-gateway", kind: "transport", source: "client", target: "gateway" },
    { id: "gateway-server", kind: "routes", source: "gateway", target: "server" },
    { id: "server-tool", kind: "exposes", source: "server", target: "tool" },
    { id: "tool-task", kind: "starts", source: "tool", target: "task" },
  ],
} as const satisfies McpGraphDocument

const trace = {
  schemaVersion: "1",
  id: "field-research-run-001",
  graphId: graph.id,
  name: "Research a remote launch site",
  events: [
    {
      id: "event-01",
      sequence: 0,
      atMs: 0,
      nodeId: "client",
      kind: "node.started",
      channel: "effect",
      summary: "Client fiber started",
      payload: { fiber: "fiber-101" },
    },
    {
      id: "event-02",
      sequence: 1,
      atMs: 220,
      nodeId: "client",
      kind: "message.sent",
      channel: "mcp",
      summary: "Call research.site",
      correlationId: "rpc-17",
      payload: {
        jsonrpc: "2.0",
        id: 17,
        method: "tools/call",
        params: { name: "research.site", arguments: { site: "LC-41" } },
      },
    },
    {
      id: "event-03",
      sequence: 2,
      atMs: 440,
      nodeId: "gateway",
      kind: "node.started",
      channel: "effect",
      summary: "Gateway route selected",
      correlationId: "rpc-17",
      payload: { capability: "tools", target: "field-operations" },
    },
    {
      id: "event-04",
      sequence: 3,
      atMs: 660,
      nodeId: "server",
      kind: "message.received",
      channel: "mcp",
      summary: "Vertical server received request",
      correlationId: "rpc-17",
      payload: { method: "tools/call", name: "research.site" },
    },
    {
      id: "event-05",
      sequence: 4,
      atMs: 820,
      nodeId: "server",
      kind: "node.started",
      channel: "effect",
      summary: "Request scope opened",
      correlationId: "rpc-17",
      payload: { scope: "request-17" },
    },
    {
      id: "event-06",
      sequence: 5,
      atMs: 1040,
      nodeId: "tool",
      kind: "node.started",
      channel: "effect",
      summary: "Tool handler entered",
      correlationId: "rpc-17",
      payload: { handler: "research.site" },
    },
    {
      id: "event-07",
      sequence: 6,
      atMs: 1280,
      nodeId: "task",
      kind: "node.started",
      channel: "task",
      summary: "Task created atomically",
      correlationId: "task-7KF2",
      payload: { taskId: "task-7KF2", status: "working" },
    },
    {
      id: "event-08",
      sequence: 7,
      atMs: 1680,
      nodeId: "task",
      kind: "node.waiting",
      channel: "task",
      summary: "Awaiting field observations",
      correlationId: "task-7KF2",
      payload: { status: "working", pollAfterMs: 1000 },
    },
    {
      id: "event-09",
      sequence: 8,
      atMs: 2360,
      nodeId: "task",
      kind: "node.completed",
      channel: "task",
      summary: "Task completed with observations",
      correlationId: "task-7KF2",
      payload: { status: "completed", observations: 12 },
    },
    {
      id: "event-10",
      sequence: 9,
      atMs: 2520,
      nodeId: "tool",
      kind: "node.completed",
      channel: "effect",
      summary: "Tool produced final result",
      correlationId: "rpc-17",
      payload: { resultType: "complete", observations: 12 },
    },
    {
      id: "event-11",
      sequence: 10,
      atMs: 2680,
      nodeId: "server",
      kind: "node.completed",
      channel: "effect",
      summary: "Request scope closed",
      correlationId: "rpc-17",
      payload: { exit: "success" },
    },
    {
      id: "event-12",
      sequence: 11,
      atMs: 2860,
      nodeId: "gateway",
      kind: "node.completed",
      channel: "effect",
      summary: "Gateway returned final result",
      correlationId: "rpc-17",
      payload: { target: "field-operations" },
    },
    {
      id: "event-13",
      sequence: 12,
      atMs: 3080,
      nodeId: "client",
      kind: "message.received",
      channel: "mcp",
      summary: "Client received CallToolResult",
      correlationId: "rpc-17",
      payload: { jsonrpc: "2.0", id: 17, result: { resultType: "complete" } },
    },
    {
      id: "event-14",
      sequence: 13,
      atMs: 3220,
      nodeId: "client",
      kind: "node.completed",
      channel: "effect",
      summary: "Client fiber completed",
      payload: { exit: "success" },
    },
  ],
} as const satisfies McpTraceDocument

export const gatewayTaskScenario = { graph, trace }
