import { Effect } from "effect"
import { adaptAppsPublicEventSource } from "../apps/AppsTraceAdapter"
import { makeProjectBundle } from "../authoring/McpProjectBundleIO"
import { withGraphRevision } from "../model/GraphFingerprint"
import type { McpGraphDocument } from "../model/McpGraphDocument"
import type { McpTraceEvent } from "../model/McpTraceDocument"

const makeProfessionalGraph = (): McpGraphDocument =>
  withGraphRevision({
    schemaVersion: "2",
    id: "professional-gateway-tasks-apps",
    name: "Professional gateway, Tasks, and Apps",
    description:
      "A gateway-routed vertical server with async Tasks and a stable-profile Apps fixture",
    nodes: [
      {
        id: "client",
        kind: "client",
        label: "Operations client",
        description: "Calls the field operations gateway",
        position: { x: 35, y: 35 },
        config: { transport: "streamable-http" },
      },
      {
        id: "gateway",
        kind: "gateway",
        label: "Capability gateway",
        description: "Routes by advertised capability",
        position: { x: 250, y: 35 },
        config: { strategy: "capability" },
      },
      {
        id: "server",
        kind: "server",
        label: "Field operations",
        description: "Vertical server for field observations",
        position: { x: 465, y: 35 },
        config: { domain: "field-operations" },
      },
      {
        id: "tool",
        kind: "tool",
        label: "observations.collect",
        description: "Starts an asynchronous collection task",
        position: { x: 700, y: 20 },
        config: { resultType: "task" },
      },
      {
        id: "task",
        kind: "task",
        label: "Collection task",
        description: "Tracks asynchronous field work",
        position: { x: 700, y: 185 },
        config: { pollingIntervalMs: 1000 },
      },
      {
        id: "app-resource",
        kind: "app-resource",
        label: "Observations UI resource",
        description: "Fixture linkage for the observations view",
        position: { x: 465, y: 235 },
        config: { uri: "ui://field-operations/observations", profile: "stable" },
      },
      {
        id: "app-view",
        kind: "app-view",
        label: "Observations view",
        description: "Stable-profile fixture view",
        position: { x: 250, y: 235 },
        config: { sandbox: true, profile: "stable" },
      },
      {
        id: "app-host",
        kind: "app-host",
        label: "Operations host",
        description: "Fixture-only host declaration",
        position: { x: 35, y: 235 },
        config: { profile: "stable" },
      },
    ],
    edges: [
      { id: "client-gateway", kind: "transport", source: "client", target: "gateway" },
      { id: "gateway-server", kind: "routes", source: "gateway", target: "server" },
      { id: "server-tool", kind: "exposes", source: "server", target: "tool" },
      { id: "tool-task", kind: "starts", source: "tool", target: "task" },
      { id: "server-app-resource", kind: "exposes", source: "server", target: "app-resource" },
      { id: "tool-app-resource", kind: "renders", source: "tool", target: "app-resource" },
      { id: "app-resource-view", kind: "renders", source: "app-resource", target: "app-view" },
      { id: "app-host-view", kind: "hosts", source: "app-host", target: "app-view" },
    ],
  })

const coreEvents = (): ReadonlyArray<McpTraceEvent> => [
  {
    id: "event-01",
    sequence: 0,
    atMs: 0,
    nodeId: "client",
    edgeId: "client-gateway",
    kind: "wire.message-sent",
    family: "wire",
    channel: "mcp",
    summary: "Call observations.collect",
    correlationId: "professional-call-1",
    protocol: { direction: "send", jsonrpc: "2.0", requestId: 1, method: "tools/call" },
    payload: { method: "tools/call", name: "observations.collect" },
  },
  {
    id: "event-02",
    sequence: 1,
    atMs: 100,
    nodeId: "gateway",
    edgeId: "gateway-server",
    kind: "runtime.started",
    family: "runtime",
    channel: "effect",
    summary: "Gateway selected field operations",
    correlationId: "professional-call-1",
    payload: { target: "field-operations" },
  },
  {
    id: "event-03",
    sequence: 2,
    atMs: 220,
    nodeId: "server",
    edgeId: "gateway-server",
    kind: "runtime.started",
    family: "runtime",
    channel: "effect",
    summary: "Vertical server opened request scope",
    correlationId: "professional-call-1",
    payload: { domain: "field-operations" },
  },
  {
    id: "event-04",
    sequence: 3,
    atMs: 360,
    nodeId: "tool",
    edgeId: "server-tool",
    kind: "runtime.started",
    family: "runtime",
    channel: "effect",
    summary: "Task-backed tool started",
    correlationId: "professional-call-1",
    payload: { resultType: "task" },
  },
  {
    id: "event-05",
    sequence: 4,
    atMs: 520,
    nodeId: "task",
    edgeId: "tool-task",
    kind: "tasks.created",
    family: "tasks",
    channel: "tasks",
    summary: "Collection task created",
    correlationId: "professional-task-1",
    payload: { status: "working" },
  },
  {
    id: "event-06",
    sequence: 5,
    atMs: 760,
    nodeId: "task",
    kind: "tasks.waiting",
    family: "tasks",
    channel: "tasks",
    summary: "Collection task waiting",
    correlationId: "professional-task-1",
    payload: { status: "working", pollAfterMs: 1000 },
  },
  {
    id: "event-07",
    sequence: 6,
    atMs: 1220,
    nodeId: "task",
    kind: "tasks.completed",
    family: "tasks",
    channel: "tasks",
    summary: "Collection task completed",
    correlationId: "professional-task-1",
    payload: { status: "completed", observations: 12 },
  },
]

const makeAppsSession = (graph: McpGraphDocument) => ({
  schemaVersion: "1",
  kind: "mcp-apps-public-session",
  id: "professional-apps-fixture-run",
  name: "Professional gateway, Tasks, and Apps fixture",
  extensionId: "io.modelcontextprotocol/ui",
  profile: "stable",
  contract: {
    status: "stable-profile-fixture",
    mimeType: "text/html;profile=mcp-app",
    uiProtocolVersion: "2026-01-26",
  },
  provenance: {
    source: "declared-fixture",
    fixtureId: "stable-view-lifecycle",
    declaration: "fixture-only",
  },
  graph,
  resource: {
    uri: "ui://field-operations/observations",
    nodeId: "app-resource",
    linkedNodeIds: ["server", "tool", "app-view"],
  },
  events: [
    {
      id: "apps-01",
      sequence: 7,
      atMs: 1360,
      nodeId: "app-resource",
      kind: "apps.resource-linked",
      summary: "UI resource linked to the tool result",
      correlationId: "professional-apps-1",
      policy: { kind: "none", outcome: "not-applicable" },
    },
    {
      id: "apps-02",
      sequence: 8,
      atMs: 1480,
      nodeId: "app-view",
      kind: "apps.view-loading",
      summary: "Fixture view entered loading",
      correlationId: "professional-apps-1",
      policy: { kind: "none", outcome: "not-applicable" },
    },
    {
      id: "apps-03",
      sequence: 9,
      atMs: 1580,
      nodeId: "app-host",
      kind: "apps.consent-allowed",
      summary: "Fixture consent allowed",
      correlationId: "professional-apps-1",
      policy: { kind: "consent", outcome: "allowed" },
    },
    {
      id: "apps-04",
      sequence: 10,
      atMs: 1660,
      nodeId: "app-host",
      kind: "apps.policy-allowed",
      summary: "Fixture policy allowed",
      correlationId: "professional-apps-1",
      policy: { kind: "policy", outcome: "allowed" },
    },
    {
      id: "apps-05",
      sequence: 11,
      atMs: 1780,
      nodeId: "app-view",
      kind: "apps.view-ready",
      summary: "Fixture view declared ready",
      correlationId: "professional-apps-1",
      policy: { kind: "none", outcome: "not-applicable" },
    },
    {
      id: "apps-06",
      sequence: 12,
      atMs: 2180,
      nodeId: "app-view",
      kind: "apps.view-closed",
      summary: "Fixture view declared closed",
      correlationId: "professional-apps-1",
      policy: { kind: "none", outcome: "not-applicable" },
    },
  ],
})

export const instantiateProGatewayTasksAppsTemplate = () => {
  const graph = makeProfessionalGraph()
  return Effect.gen(function* () {
    const apps = yield* adaptAppsPublicEventSource({ read: Effect.succeed(makeAppsSession(graph)) })
    return yield* makeProjectBundle(apps.graph, {
      ...apps.trace,
      events: [...coreEvents(), ...apps.trace.events],
    })
  })
}

export { makeProfessionalGraph, makeAppsSession }
